/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Candidato;
import model.bean.Eleitor;
import model.dao.CandidatoDAO;
import model.dao.EleitorDAO;

/**
 *
 * @author Rafael
 */
public class AdminScreen extends javax.swing.JFrame {

    List<Candidato> candidatos = new CandidatoDAO().listar();
    List<Eleitor> eleitores = new EleitorDAO().list();
    CandidatoDAO candidatoDAO = new CandidatoDAO();
    Candidato candidato = new Candidato();
    Eleitor eleitor;
    EleitorDAO eleitorDAO = new EleitorDAO();

    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        initComponents();
        initComplements();
        createTableCandidato();
        createTableEleitor();
    }

    public void initComplements() {
        this.setLocationRelativeTo(null);
    }

    private void createTableCandidato() {
        DefaultTableModel dtmc = (DefaultTableModel) tbCandidato.getModel();
        for (Candidato cndt : candidatos) {
            dtmc.addRow(new Object[]{
                cndt.getName(),
                cndt.getNum(),
                cndt.getChapa()

            });
        }
    }

    private void createTableEleitor() {
        DefaultTableModel dtme = (DefaultTableModel) tbEleitor.getModel();
        for (Eleitor elt : eleitores) {
            dtme.addRow(new Object[]{
                elt.getNome(),
                elt.getRg(),
                elt.getMatricula()

            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAddCandidato = new javax.swing.JButton();
        btnAlterCandidato = new javax.swing.JButton();
        btnDelCandidato = new javax.swing.JButton();
        btnAddEleitor = new javax.swing.JButton();
        btnAlterEleitor = new javax.swing.JButton();
        btnDelEleitor = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbCandidato = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbEleitor = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/if.PNG"))); // NOI18N

        btnAddCandidato.setBackground(new java.awt.Color(255, 255, 255));
        btnAddCandidato.setText("Adicionar");
        btnAddCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCandidatoActionPerformed(evt);
            }
        });

        btnAlterCandidato.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterCandidato.setText("Alterar");
        btnAlterCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterCandidatoActionPerformed(evt);
            }
        });

        btnDelCandidato.setBackground(new java.awt.Color(255, 255, 255));
        btnDelCandidato.setText("Excluir");
        btnDelCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCandidatoActionPerformed(evt);
            }
        });

        btnAddEleitor.setBackground(new java.awt.Color(255, 255, 255));
        btnAddEleitor.setText("Adicionar");
        btnAddEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEleitorActionPerformed(evt);
            }
        });

        btnAlterEleitor.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterEleitor.setText("Alterar");
        btnAlterEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterEleitorActionPerformed(evt);
            }
        });

        btnDelEleitor.setBackground(new java.awt.Color(255, 255, 255));
        btnDelEleitor.setText("Excluir");
        btnDelEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelEleitorActionPerformed(evt);
            }
        });

        tbCandidato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Número", "Chapa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCandidato.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tbCandidato);
        if (tbCandidato.getColumnModel().getColumnCount() > 0) {
            tbCandidato.getColumnModel().getColumn(0).setResizable(false);
            tbCandidato.getColumnModel().getColumn(1).setResizable(false);
            tbCandidato.getColumnModel().getColumn(2).setResizable(false);
        }

        tbEleitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "RG", "Matrícula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEleitor.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tbEleitor);
        if (tbEleitor.getColumnModel().getColumnCount() > 0) {
            tbEleitor.getColumnModel().getColumn(0).setResizable(false);
            tbEleitor.getColumnModel().getColumn(0).setPreferredWidth(150);
            tbEleitor.getColumnModel().getColumn(1).setResizable(false);
            tbEleitor.getColumnModel().getColumn(2).setResizable(false);
        }

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Computar Votos");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("ELEITORES");

        jLabel2.setText("CANDIDATOS");

        btnBack.setText("Voltar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAlterCandidato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAlterEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAddEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(btnVoltar))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddCandidato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterCandidato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelCandidato))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnAddEleitor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAlterEleitor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDelEleitor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                            .addComponent(btnBack))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCandidatoActionPerformed
        CandidatoScreen cs = new CandidatoScreen();
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddCandidatoActionPerformed

    private void btnAddEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEleitorActionPerformed
        EleitorScreen es = new EleitorScreen();
        es.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAddEleitorActionPerformed

    private void btnAlterCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterCandidatoActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tbCandidato.getModel();
        candidato = candidatoDAO.select((int) dtm.getValueAt(tbCandidato.getSelectedRow(), 1));
        CandidatoScreen cs = new CandidatoScreen(candidato);
        cs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAlterCandidatoActionPerformed

    private void btnDelCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCandidatoActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tbCandidato.getModel();
        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?");
        if (resposta == 0) {
            if (tbCandidato.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um candidato para ser excluído");
            } else {
                Object obj = dtm.getValueAt(tbCandidato.getSelectedRow(), 1);
                int excluir = (int) obj;
                candidatoDAO.excluir(excluir);
                dtm.removeRow(tbCandidato.getSelectedRow());
            }
        } else {

        }
    }//GEN-LAST:event_btnDelCandidatoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        AdminComputeVoteScreen acvs = new AdminComputeVoteScreen();
        acvs.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainScreen ms = new MainScreen();
        ms.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAlterEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterEleitorActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tbEleitor.getModel();
        eleitor = eleitorDAO.selectByRg(String.valueOf(dtm.getValueAt(tbEleitor.getSelectedRow(), 1)));
        EleitorScreen es = new EleitorScreen(eleitor);
        es.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAlterEleitorActionPerformed

    private void btnDelEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelEleitorActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tbEleitor.getModel();
        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?");
        if (resposta == 0) {
            if (tbEleitor.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um candidato para ser excluído");
            } else {
                Object obj = dtm.getValueAt(tbEleitor.getSelectedRow(), 1);
                String excluir = String.valueOf(obj);
                eleitorDAO.delete(excluir);
                dtm.removeRow(tbEleitor.getSelectedRow());
            }
        } else {

        }
    }//GEN-LAST:event_btnDelEleitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCandidato;
    private javax.swing.JButton btnAddEleitor;
    private javax.swing.JButton btnAlterCandidato;
    private javax.swing.JButton btnAlterEleitor;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelCandidato;
    private javax.swing.JButton btnDelEleitor;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tbCandidato;
    private javax.swing.JTable tbEleitor;
    // End of variables declaration//GEN-END:variables
}
